/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ConfirmDialog: typeof import('./components/core/ConfirmDialog.vue')['default']
    Dialog: typeof import('./components/core/Dialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Item: typeof import('./components/post/item.vue')['default']
    PostItem: typeof import('./components/post/PostItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDialog: typeof import('./components/core/TheDialog.vue')['default']
    Upsert: typeof import('./components/post/Upsert.vue')['default']
  }
}
